import { ArrowLeft, ArrowRight, ArrowUpRight, Check, Minus, Plus, Tag, Trash2, Truck } from "lucide-react";
import { Link } from "wouter";
import { formatBDT } from "@/lib/catalog";
import { useStore } from "@/lib/store";

export default function Cart() {
  const { cartProducts, cartCount, subtotal, discount, delivery, total, coupon, setCoupon, updateQuantity, removeFromCart, clearCart } = useStore();
  const physical = cartProducts.filter(line => line.product.kind === "physical");
  const digital = cartProducts.filter(line => line.product.kind === "digital");
  const applyCoupon = (event: React.FormEvent) => { event.preventDefault(); };
  const section = (title: string, lines: typeof cartProducts, description: string) => <section className="cart-section"><div className="cart-section-head"><div><span className="eyebrow">{title}</span><h2>{lines.length} {lines.length === 1 ? "signal" : "signals"}</h2></div><p>{description}</p></div>{lines.length === 0 ? <div className="cart-empty-line"><span>No {title.toLowerCase()} in this cart.</span><Link href="/shop">Keep browsing <ArrowRight size={15} /></Link></div> : <div className="cart-lines">{lines.map(({ product, quantity }) => <div className="cart-line" key={product.id}><img src={product.image} alt="" /><div className="cart-line-copy"><span className="eyebrow">{product.eyebrow}</span><Link href={`/product/${product.slug}`}><h3>{product.name}</h3></Link><p>{product.delivery}</p><button className="remove-link" onClick={() => removeFromCart(product.id)}><Trash2 size={13} /> Remove</button></div><div className="cart-line-qty"><div className="quantity-control"><button onClick={() => updateQuantity(product.id, quantity - 1)} aria-label={`Decrease ${product.name} quantity`}><Minus size={14} /></button><span>{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)} aria-label={`Increase ${product.name} quantity`}><Plus size={14} /></button></div></div><strong className="cart-line-price">{formatBDT(product.price * quantity)}</strong></div>)}</div>}</section>;
  return <div className="page-shell inner-page"><section className="page-title section-pad"><div className="section-kicker"><span>01 / UTILITY</span><span>{cartCount} ITEMS / READY TO REVIEW</span></div><div className="page-title-row"><div><span className="eyebrow">YOUR CART</span><h1>The current<br /><em>signal.</em></h1></div><p>Review the physical and digital parts separately, apply your offer, then move to a transparent order summary.</p></div></section>{cartProducts.length === 0 ? <div className="section-pad empty-state large-empty"><Check size={28} /><h2>Your cart is quiet.</h2><p>Build a better everyday kit from the current drop.</p><Link className="button button-primary" href="/shop">Explore the drop <ArrowUpRight size={16} /></Link></div> : <div className="cart-layout section-pad"><div className="cart-main">{section("Physical goods", physical, "Delivery estimate is shown before checkout.")}{section("Digital goods", digital, "Instant access after manual payment approval.")}<div className="cart-note"><Truck size={18} /><span><b>Free delivery over ৳9,520.</b> You are {subtotal >= 9520 ? "already there." : `৳${Math.max(0, 9520 - subtotal).toLocaleString()} away from free delivery.`}</span></div></div><aside className="summary-card"><div className="summary-card-head"><span className="eyebrow">ORDER REVIEW</span><h2>Make it clear.</h2></div><form className="coupon-form" onSubmit={applyCoupon}><label htmlFor="coupon">Coupon or signal code</label><div><Tag size={15} /><input id="coupon" value={coupon} onChange={event => setCoupon(event.target.value)} placeholder="Try SIGNAL20" /><button type="submit">Apply</button></div>{coupon && coupon.toUpperCase() === "SIGNAL20" && <span className="status-success"><Check size={13} /> 20% signal discount applied</span>}</form><div className="summary-rows"><div><span>Subtotal ({cartCount} items)</span><b>{formatBDT(subtotal)}</b></div><div><span>Signal discount</span><b className="text-accent">− {formatBDT(discount)}</b></div><div><span>Delivery</span><b>{delivery === 0 ? "Free" : formatBDT(delivery)}</b></div><div className="summary-total"><span>Total</span><strong>{formatBDT(total)}</strong></div></div><Link className="button button-primary button-wide" href="/checkout">Continue to checkout <ArrowUpRight size={16} /></Link><button className="text-link center-link" onClick={clearCart}>Clear cart</button><div className="summary-trust"><span><Check size={14} /> Secure checkout handoff</span><span><Check size={14} /> Bangladesh pricing</span></div></aside></div>}</div>;
}
