import type { CSSProperties } from "react";
import { ArrowRight, ArrowUpRight, Check, Download, Headphones, Mail, Megaphone, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { Link } from "wouter";
import { campaigns, formatBDT, products } from "@/lib/catalog";
import { useStore } from "@/lib/store";

export function Campaigns() {
  return <div className="page-shell inner-page"><section className="page-title section-pad"><div className="section-kicker"><span>01 / CAMPAIGN BOARD</span><span>LIVE / SCHEDULED / SIGNAL</span></div><div className="page-title-row"><div><span className="eyebrow">CURRENT CAMPAIGNS</span><h1>Make the<br /><em>signal louder.</em></h1></div><p>Offers are short, visible, and honest. Find the active drop, see what qualifies, and keep the details close to the price.</p></div></section><section className="campaign-feature section-pad section-dark"><div className="campaign-feature-copy"><span className="eyebrow">FLASH // 20</span><h2>Selected tech.<br /><em>Sharper price.</em></h2><p>Save 20% on selected tech through the current drop. The discount is visible before checkout and never hidden in the last step.</p><div className="campaign-stats"><span><b>20%</b><small>selected discount</small></span><span><b>03</b><small>signals included</small></span><span><b>06—26</b><small>campaign code</small></span></div><Link className="button button-primary" href="/shop">Shop selected signals <ArrowUpRight size={16} /></Link></div><div className="campaign-feature-art"><div className="campaign-glow" /><img src={products[0].image} alt="Orbit Buds campaign visual" /><span>CAMPAIGN<br /><b>LIVE</b></span></div></section><section className="section-pad campaign-list"><div className="section-kicker"><span>DROP NOTES</span><span>03 ACTIVE SIGNALS</span></div><div className="campaign-list-grid">{campaigns.map((campaign, index) => <Link href="/shop" className="campaign-list-card" key={campaign.code} style={{ "--accent": campaign.color } as CSSProperties}><span className="campaign-number">0{index + 1}</span><div><span className="eyebrow">{campaign.code}</span><h2>{campaign.title}</h2><p>{campaign.copy}</p></div><ArrowUpRight size={18} /></Link>)}</div></section></div>;
}

export function DigitalVault() {
  const { addToCart } = useStore();
  const digital = products.filter(product => product.kind === "digital");
  return <div className="page-shell inner-page"><section className="vault-intro section-pad section-dark"><div><span className="eyebrow">DIGITAL / VAULT</span><h1>Ideas that<br /><em>travel light.</em></h1><p>Downloadable goods with a clear purpose: guides, wallpapers, templates, and ideas that do not need a delivery truck.</p><div className="vault-intro-actions"><Link className="button button-primary" href="/shop?category=Digital">Browse digital goods <ArrowUpRight size={16} /></Link><span><Download size={15} /> Approval-gated delivery</span></div></div><div className="vault-intro-visual"><img src={digital[0].image} alt="Digital vault artwork" /><div className="vault-file-card"><span>PDF / EPUB</span><b>01</b><small>READY WHEN YOU ARE</small></div></div></section><section className="section-pad digital-grid-section"><div className="section-kicker"><span>01 / DIGITAL GOODS</span><span>{digital.length} DOWNLOADS</span></div><div className="digital-grid">{digital.map(product => <article className="digital-card" key={product.id}><div className="digital-card-art"><img src={product.image} alt="" /><span><Download size={15} /> DOWNLOAD</span></div><div><span className="eyebrow">{product.eyebrow}</span><h2>{product.name}</h2><p>{product.description}</p><div className="digital-buy"><strong>{formatBDT(product.price)}</strong><button className="button button-outline" onClick={() => addToCart(product)}>Add to cart <PlusIcon /></button></div></div></article>)}</div></section><section className="digital-trust section-pad section-dark"><div><span className="eyebrow">HOW IT WORKS</span><h2>Clear in three<br /><em>small steps.</em></h2></div><div className="steps-grid">{[{ icon: <Sparkles />, title: "Choose a signal", copy: "Add a guide, wallpaper, or other digital idea to your cart." }, { icon: <ShieldCheck />, title: "Review payment", copy: "We manually review your payment before delivery." }, { icon: <Download />, title: "Download", copy: "Your approved file appears in your account vault." }].map((step, index) => <div className="step-card" key={step.title}><span>0{index + 1}</span>{step.icon}<h3>{step.title}</h3><p>{step.copy}</p></div>)}</div></section></div>;
}
function PlusIcon() { return <ArrowRight size={14} />; }

export function InfoPage({ type }: { type: "support" | "returns" | "why" }) {
  const content = type === "returns" ? { label: "POLICY / RETURNS", title: <>Returns<br /><em>without static.</em></>, copy: "Eligible physical products can be returned within 7 days of delivery when they are unused and in original condition.", icon: <Truck size={22} /> } : type === "why" ? { label: "SIGNAL / WHY RYK", title: <>Useful things.<br /><em>Clear reason.</em></>, copy: "RYK AXIS Plus is a Bangladesh-first independent store for the small objects and digital ideas that make a day move better.", icon: <Sparkles size={22} /> } : { label: "SUPPORT / DIRECT LINE", title: <>Need a clearer<br /><em>signal?</em></>, copy: "Tell us what happened. We will keep the answer as direct as the storefront.", icon: <Headphones size={22} /> };
  return <div className="page-shell inner-page"><section className="info-hero section-pad section-dark"><span className="eyebrow">{content.label}</span><h1>{content.title}</h1><p>{content.copy}</p><div className="info-hero-icon">{content.icon}</div></section>{type === "support" ? <section className="section-pad support-grid"><div className="support-card"><Mail size={20} /><span className="eyebrow">EMAIL</span><h2>support@rykaxis.plus</h2><p>Replies typically land within one business day.</p><button className="button button-primary">Start a support note <ArrowUpRight size={15} /></button></div><div className="support-card"><Megaphone size={20} /><span className="eyebrow">ORDER HELP</span><h2>Track your signal</h2><p>Sign in to see review, dispatch, delivery, and digital-download status.</p><Link className="button button-outline" href="/account/orders">Open order status <ArrowRight size={15} /></Link></div></section> : <section className="section-pad policy-content"><div><span className="eyebrow">{type === "why" ? "OUR SIGNAL" : "THE SHORT VERSION"}</span><h2>{type === "why" ? "Curated, transparent, built for Bangladesh." : "What to expect."}</h2></div><div className="policy-copy"><p>We keep prices in Bangladeshi taka, make delivery estimates visible, and keep payment approval separate from the moment you place an order. That means fewer surprises and a better record of what happened.</p><ul>{["Clear product status before checkout", "Manual review before physical dispatch", "Digital delivery after approval", "Support that keeps the order context"].map(item => <li key={item}><Check size={15} /> {item}</li>)}</ul><Link className="text-link" href="/shop">Return to the current drop <ArrowRight size={15} /></Link></div></section>}</div>;
}
