import type { CSSProperties } from "react";
import { ArrowDownRight, ArrowUpRight, CirclePlay, Heart, Plus, ShieldCheck, Truck, Zap } from "lucide-react";
import { Link } from "wouter";
import { campaigns, categories, formatBDT, products } from "@/lib/catalog";
import { useStore } from "@/lib/store";

function ProductCard({ product, index }: { product: typeof products[number]; index: number }) {
  const { addToCart, wishlist, toggleWishlist } = useStore();
  const soldOut = product.stock === 0;
  return <article className="product-card">
    <div className="product-media"><img src={product.image} alt={`${product.name} product view`} /><span className="product-index">0{index + 1}</span><button className={`wishlist-button ${wishlist.includes(product.id) ? "is-saved" : ""}`} onClick={() => toggleWishlist(product.id)} aria-label={`${wishlist.includes(product.id) ? "Remove" : "Add"} ${product.name} ${wishlist.includes(product.id) ? "from" : "to"} wishlist`}><Heart size={16} fill={wishlist.includes(product.id) ? "currentColor" : "none"} /></button><span className="product-tag">{product.tags[0]}</span></div>
    <div className="product-card-copy"><div className="product-card-meta"><span>{product.eyebrow}</span><span className="rating">★ {product.rating}</span></div><Link href={`/product/${product.slug}`}><h3>{product.name}</h3></Link><p>{product.description}</p><div className="product-card-buy"><div><strong>{formatBDT(product.price)}</strong>{product.compareAt && <del>{formatBDT(product.compareAt)}</del>}</div><button className="add-icon" disabled={soldOut} onClick={() => addToCart(product)} aria-label={soldOut ? `${product.name} is sold out` : `Add ${product.name} to cart`}>{soldOut ? "—" : <Plus size={17} />}</button></div></div>
  </article>;
}

export default function Home() {
  const { addToCart } = useStore();
  const featured = products[0];
  return <div className="page-shell">
    <section className="home-hero section-pad"><div className="hero-copy"><span className="eyebrow eyebrow-live"><span className="pulse-dot" /> MULTI-BRAND TECH / DIGITAL GOODS</span><h1>Find your<br /><span>next axis.</span></h1><p>Electric essentials and digital ideas, curated for the way you move through the world.</p><div className="hero-actions"><Link className="button button-primary" href="/shop">Explore the drop <ArrowUpRight size={17} /></Link><Link className="button button-quiet" href="/seller">Seller mode <span>↗</span></Link></div><div className="hero-coordinates"><span>23°41' N<br /><i>90°24' E</i></span><span>CURATED<br /><b>06—26</b></span></div></div><div className="hero-visual"><img src={featured.image} alt="Layered product composition featuring wireless earbuds" /><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-floating-note"><span>01 / 07</span><b>SMART GOODS<br />FOR REAL LIFE.</b></div><div className="hero-signal">SIGNAL<br /><b>LIVE</b></div></div></section>
    <section className="campaign-bar" aria-label="Current campaign"><div className="campaign-label"><span className="pulse-dot" /> CAMPAIGN LIVE</div><strong>FLASH // SAVE 20% ON SELECTED TECH</strong><Link href="/campaigns">Manage campaign <ArrowUpRight size={15} /></Link><span className="campaign-code">06—26</span></section>
    <section className="motion-drop section-pad section-dark"><div className="section-kicker"><span>01 / FEATURED SIGNAL</span><span>ONE SIGNAL / EVERY FIVE SECONDS</span></div><div className="motion-grid"><div className="motion-copy"><span className="eyebrow">AUDIO / PHYSICAL</span><h2>One signal.<br /><em>Every five seconds.</em></h2><p>Explore the drop as a living sequence. Each object is selected for the small ways it makes a day feel clearer.</p><Link className="text-link" href={`/product/${featured.slug}`}>View featured signal <ArrowUpRight size={15} /></Link><div className="motion-controls"><button aria-label="Previous featured product">←</button><span>01 <i>/</i> 07</span><button aria-label="Next featured product">→</button></div></div><div className="motion-feature"><img src={featured.image} alt="Orbit Buds / 02" /><div className="motion-feature-label"><span>NEW DROP</span><b>{featured.name}</b><small>{formatBDT(featured.price)} · {featured.delivery}</small></div><button className="motion-add" onClick={() => addToCart(featured)} aria-label={`Add ${featured.name} to cart`}><Plus size={20} /></button></div></div></section>
    <section className="catalog-intro section-pad" id="shop"><div className="section-kicker"><span>02 / THE DROP</span><span>07 ITEMS / BD ONLY</span></div><div className="split-heading"><div><span className="eyebrow">SELECTED SIGNALS</span><h2>Useful things.<br /><em>Sharper signal.</em></h2></div><div><p>Objects and downloads with a reason to exist. Every price localized to <strong>Bangladesh</strong>, with no hidden switchbacks.</p><Link className="text-link" href="/shop">Open the full catalog <ArrowUpRight size={15} /></Link></div></div><div className="category-row" aria-label="Shop categories">{categories.map((category, index) => <Link key={category} href={index === 0 ? "/shop" : `/shop?category=${encodeURIComponent(category)}`} className={index === 0 ? "is-active" : ""}>{category}<span>{String(index + 1).padStart(2, "0")}</span></Link>)}</div><div className="product-grid">{products.slice(0, 6).map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div><div className="center-action"><Link className="button button-outline" href="/shop">Browse all 07 items <ArrowUpRight size={16} /></Link></div></section>
    <section className="vault-section section-pad section-dark"><div className="vault-visual"><img src={products[3].image} alt="Digital vault abstract cover art" /><span className="vault-stamp">E-BOOK<br /><b>01</b></span></div><div className="vault-copy"><span className="eyebrow">03 / DIGITAL VAULT</span><h2>Good ideas<br /><em>travel light.</em></h2><p>Make room for digital goods too: e-books, guides, templates, and downloads can live in the same premium storefront as physical inventory.</p><div className="vault-badges"><span><ShieldCheck size={16} /> Manual payment review</span><span><Zap size={16} /> Approval-gated delivery</span><span><Truck size={16} /> Bangladesh pricing</span></div><Link className="button button-primary" href="/digital-vault">Browse digital vault <ArrowUpRight size={17} /></Link></div></section>
    <section className="why-section section-pad"><div className="section-kicker"><span>04 / WHY RYK AXIS PLUS</span><span>DESIGNED FOR THE NEXT EVERYDAY</span></div><div className="why-grid">{[{ icon: <Zap />, title: "Curated, not crowded", copy: "A smaller signal makes the right object easier to find." }, { icon: <ShieldCheck />, title: "Clear at every step", copy: "Prices, delivery, stock, and payment review stay visible." }, { icon: <CirclePlay />, title: "Built to move", copy: "Physical goods and digital ideas in one clean orbit." }].map(item => <div className="why-card" key={item.title}><div className="why-icon">{item.icon}</div><h3>{item.title}</h3><p>{item.copy}</p><ArrowDownRight size={18} /></div>)}</div></section>
    <section className="campaign-cards section-pad section-dark"><div className="split-heading"><div><span className="eyebrow">SIGNAL BOARD</span><h2>Drop notes<br /><em>for later.</em></h2></div><p>Save a collection, share a signal, or come back when the mood is right. The store remembers the useful things.</p></div><div className="campaign-grid">{campaigns.map(campaign => <Link href="/campaigns" className="campaign-card" key={campaign.code} style={{ "--accent": campaign.color } as CSSProperties}><span>{campaign.code}</span><h3>{campaign.title}</h3><p>{campaign.copy}</p><ArrowUpRight size={17} /></Link>)}</div></section>
  </div>;
}
